# Generated by Django 3.2.3 on 2021-07-18 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firsname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.login')),
            ],
        ),
    ]
