# Generated by Django 3.2.3 on 2021-08-20 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_auto_20210726_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='date',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='phone',
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mynote', models.CharField(max_length=100)),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(max_length=20)),
                ('height', models.IntegerField(max_length=20)),
                ('weight', models.IntegerField(max_length=20)),
                ('medcondition', models.CharField(max_length=20)),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.login')),
            ],
        ),
    ]
