# Generated by Django 3.2.3 on 2021-08-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_auto_20210820_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='diet',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='diet',
            name='weight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(),
        ),
    ]
