# Generated by Django 3.2.3 on 2021-08-24 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_auto_20210820_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Udetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=20)),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.login')),
            ],
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
