# Generated by Django 3.2.3 on 2021-08-24 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_auto_20210824_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='loginid',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='todoapp.login'),
            preserve_default=False,
        ),
    ]
