# Generated by Django 3.2.3 on 2021-09-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_task_loginid'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
